# Generated by Django 3.1.2 on 2021-01-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('DNI', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='documento')),
                ('name', models.CharField(max_length=200, verbose_name='nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birth', models.DateField(verbose_name='Fecha nacimineto')),
                ('creation_day', models.DateField(verbose_name='Fecha creacion')),
                ('imge', models.ImageField(upload_to='', verbose_name='foto')),
            ],
        ),
    ]
